name: signin_with_linkedin
description: A flutter plugin that helps to sign in with linkedin (Social sign in)
version: 1.0.1
homepage: https://auberginesolutions.com
repository: https://github.com/YashMakan/signin_with_linkedin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http:
  json_annotation:
  json_serializable:
  uuid:
  webview_flutter:

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

