name: signin_with_linkedin
description: A flutter plugin that helps to sign in with linkedin (Social sign in)
version: 1.0.0
homepage: https://auberginesolutions.com
repository: https://github.com/nayanAubie/signin_with_linkedin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  uuid: ^4.4.0
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

