name: signin_with_linkedin
description: A flutter plugin that helps to sign in with linkedin (Social sign in)
version: 0.0.1
homepage: https://auberginesolutions.com
repository: https://github.com/nayanAubie/signin_with_linkedin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

